SELECT
 LOC_TRAIT_VAL_CD,
 LOC_TRAIT_CD,
 LOC_TRAIT_VAL_DESC 
FROM
 {{ ref('LOCATION_TRAIT_VALUE_WRK_7') }}  
UNION ALL 
SELECT
 LOC_TRAIT_VAL_CD,
 LOC_TRAIT_CD,
 LOC_TRAIT_VAL_DESC 
FROM
 {{ ref('LOCATION_TRAIT_VALUE_WRK_6') }}  
UNION ALL 
SELECT
 LOC_TRAIT_VAL_CD,
 LOC_TRAIT_CD,
 LOC_TRAIT_VAL_DESC 
FROM
 {{ ref('LOCATION_TRAIT_VALUE_WRK_5') }}  
UNION ALL 
SELECT
 LOC_TRAIT_VAL_CD,
 LOC_TRAIT_CD,
 LOC_TRAIT_VAL_DESC 
FROM
 {{ ref('LOCATION_TRAIT_VALUE_WRK_9') }};