SELECT
  LOC_TRAIT_VAL_CD as LOC_TRAIT_VAL_CD_lkp,
  LOC_TRAIT_CD as LOC_TRAIT_CD_lkp,
  LOC_TRAIT_VAL_DESC  as LOC_TRAIT_VAL_DESC_lkp 
 FROM
  EDWDATA.LOCATION_TRAIT_VALUE     
 WHERE
  LOC_TRAIT_CD = 'DEMO'