SELECT 
 LOC_TRAIT_VAL_CD,
 LOC_TRAIT_CD,
 LOC_TRAIT_VAL_DESC
 FROM {{ ref('var(LOCATION_TRAIT_VALUE)_TMP1') }}
 union
 SELECT 
 LOC_TRAIT_VAL_CD,
 LOC_TRAIT_CD,
 LOC_TRAIT_VAL_DESC
 FROM {{ ref('LOCATION_TRAIT_VALUE_TMP2') }}